package it.fantasytoolkit.dungeongenerator;

import java.util.ArrayDeque;
import java.util.Deque;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import it.fantasytoolkit.dungeongenerator.result.Chamber;
import it.fantasytoolkit.dungeongenerator.result.ChamberConnection;
import it.fantasytoolkit.dungeongenerator.result.DungeonResult;
import it.fantasytoolkit.dungeongenerator.result.MainEvent;
import it.fantasytoolkitcore.core.model.ChamberType;
import org.junit.jupiter.api.Test;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

public class DungeonGenerationToolTest {

    private static final int ITERATIONS = 50;

    @Test
    void simpleGeneration() {
        for (int i = 0; i < ITERATIONS; i++) {
            DungeonResult result = DungeonGenerationTool.building()
                    .numberOfChambers(8)
                    .mainEvent()
                    .mainEvent()
                    .randomPositionMainEvent()
                    .haveTraps()
                    .numberOfEnemy(7)
                    .generate();

            System.out.println(result);
        }
    }

    @Test
    void generateWithoutNumberOfChambersThrowsIllegalStateException() {
        assertThatThrownBy(() -> DungeonGenerationTool.building()
                .generate())
                .isInstanceOf(IllegalStateException.class)
                .hasMessage("Number of chambers must be set before generating a dungeon");
    }

    @Test
    void generateWithTooFewChambersThrowsIllegalStateException() {
        assertThatThrownBy(() -> DungeonGenerationTool.building()
                .numberOfChambers(1)
                .generate())
                .isInstanceOf(IllegalStateException.class)
                .hasMessage("Number of chambers must be at least 2 (entry chamber and final chamber)");
    }

    @Test
    void generateWithNegativeNumberOfEnemyThrowsIllegalStateException() {
        assertThatThrownBy(() -> DungeonGenerationTool.building()
                .numberOfChambers(4)
                .numberOfEnemy(-1)
                .generate())
                .isInstanceOf(IllegalStateException.class)
                .hasMessage("Number of enemies must not be negative");
    }

    @Test
    void generateWithNegativeNumberOfChestsThrowsIllegalStateException() {
        assertThatThrownBy(() -> DungeonGenerationTool.building()
                .numberOfChambers(4)
                .numberOfChests(-1)
                .generate())
                .isInstanceOf(IllegalStateException.class)
                .hasMessage("Number of chests must not be negative");
    }

    @Test
    void generatesRequestedNumberOfChambers() {
        DungeonResult result = DungeonGenerationTool.building()
                .numberOfChambers(6)
                .generate();

        assertThat(result.chambers()).hasSize(6);
    }

    @Test
    void generatesExactlyOneEntryAndOneFinalChamber() {
        DungeonResult result = DungeonGenerationTool.building()
                .numberOfChambers(6)
                .generate();

        List<Chamber> entryChambers = chambersOfType(result, ChamberType.ENTRY);
        List<Chamber> finalChambers = chambersOfType(result, ChamberType.FINAL);

        assertThat(entryChambers).hasSize(1);
        assertThat(entryChambers.getFirst().id()).isZero();
        assertThat(finalChambers).hasSize(1);
        assertThat(finalChambers.getFirst().id()).isEqualTo(5);
    }

    @Test
    void finalMainEventsAlwaysEndUpInTheFinalChamber() {
        DungeonResult result = DungeonGenerationTool.building()
                .numberOfChambers(6)
                .mainEvent()
                .mainEvent()
                .mainEvent()
                .generate();

        Chamber finalChamber = chambersOfType(result, ChamberType.FINAL).getFirst();

        assertThat(finalChamber.mainEvents()).hasSize(3);
    }

    @Test
    void randomPositionMainEventsNeverEndUpInTheEntryChamberAndTotalMatchesCalls() {
        DungeonResult result = DungeonGenerationTool.building()
                .numberOfChambers(6)
                .randomPositionMainEvent()
                .randomPositionMainEvent()
                .randomPositionMainEvent()
                .randomPositionMainEvent()
                .generate();

        Chamber entryChamber = chambersOfType(result, ChamberType.ENTRY).getFirst();
        assertThat(entryChamber.mainEvents()).isEmpty();

        int totalMainEvents = result.chambers().stream()
                .mapToInt(chamber -> chamber.mainEvents().size())
                .sum();
        assertThat(totalMainEvents).isEqualTo(4);
    }

    @Test
    void autoGeneratedMainEventCodesStartWithExpectedPrefixAndExplicitCodesAreKept() {
        DungeonResult result = DungeonGenerationTool.building()
                .numberOfChambers(6)
                .mainEvent()
                .mainEvent("MainEvent_A01")
                .randomPositionMainEvent()
                .generate();

        List<String> allCodes = result.chambers().stream()
                .flatMap(chamber -> chamber.mainEvents().stream())
                .map(MainEvent::code)
                .toList();

        assertThat(allCodes).contains("MainEvent_A01");
        assertThat(allCodes).filteredOn(code -> !code.equals("MainEvent_A01"))
                .allMatch(code -> code.startsWith("MainEvent_"));
    }

    @Test
    void distributesEnemiesUniformlyAcrossAllChambers() {
        for (int i = 0; i < ITERATIONS; i++) {
            int numberOfChambers = 7;
            int numberOfEnemy = 20;

            DungeonResult result = DungeonGenerationTool.building()
                    .numberOfChambers(numberOfChambers)
                    .numberOfEnemy(numberOfEnemy)
                    .generate();

            int base = numberOfEnemy / numberOfChambers;
            int sum = result.chambers().stream()
                    .mapToInt(Chamber::enemyCount)
                    .sum();

            assertThat(sum).isEqualTo(numberOfEnemy);
            assertThat(result.chambers()).allMatch(
                    chamber -> chamber.enemyCount() == base || chamber.enemyCount() == base + 1);
        }
    }

    @Test
    void distributesChestsUniformlyAcrossAllChambers() {
        for (int i = 0; i < ITERATIONS; i++) {
            int numberOfChambers = 7;
            int numberOfChests = 20;

            DungeonResult result = DungeonGenerationTool.building()
                    .numberOfChambers(numberOfChambers)
                    .numberOfChests(numberOfChests)
                    .generate();

            int base = numberOfChests / numberOfChambers;
            int sum = result.chambers().stream()
                    .mapToInt(Chamber::chestCount)
                    .sum();

            assertThat(sum).isEqualTo(numberOfChests);
            assertThat(result.chambers()).allMatch(
                    chamber -> chamber.chestCount() == base || chamber.chestCount() == base + 1);
        }
    }

    @Test
    void withoutHaveTrapsNoChamberHasTraps() {
        DungeonResult result = DungeonGenerationTool.building()
                .numberOfChambers(8)
                .generate();

        assertThat(result.numberOfTraps()).isZero();
        assertThat(result.chambers()).allMatch(chamber -> chamber.trapCount() == 0);
    }

    @Test
    void distributesTrapsUniformlyAcrossAllChambersWhenHaveTrapsIsCalled() {
        for (int i = 0; i < ITERATIONS; i++) {
            int numberOfChambers = 7;

            DungeonResult result = DungeonGenerationTool.building()
                    .numberOfChambers(numberOfChambers)
                    .haveTraps()
                    .generate();

            int numberOfTraps = result.numberOfTraps();
            int base = numberOfTraps / numberOfChambers;
            int sum = result.chambers().stream()
                    .mapToInt(Chamber::trapCount)
                    .sum();

            assertThat(numberOfTraps).isBetween(0, numberOfChambers);
            assertThat(sum).isEqualTo(numberOfTraps);
            assertThat(result.chambers()).allMatch(
                    chamber -> chamber.trapCount() == base || chamber.trapCount() == base + 1);
        }
    }

    @Test
    void dungeonIsFullyConnectedFromTheEntryChamber() {
        for (int i = 0; i < ITERATIONS; i++) {
            DungeonResult result = DungeonGenerationTool.building()
                    .numberOfChambers(10)
                    .generate();

            Set<Integer> reachableChamberIds = reachableChamberIds(result);

            assertThat(reachableChamberIds).hasSize(result.numberOfChambers());
            assertThat(degreeOf(result, 0)).isGreaterThanOrEqualTo(1);
            assertThat(degreeOf(result, result.numberOfChambers() - 1)).isGreaterThanOrEqualTo(1);
        }
    }

    private List<Chamber> chambersOfType(DungeonResult result, ChamberType type) {
        return result.chambers().stream()
                .filter(chamber -> chamber.type() == type)
                .toList();
    }

    private Set<Integer> reachableChamberIds(DungeonResult result) {
        Map<Integer, Set<Integer>> adjacency = buildAdjacency(result);

        Set<Integer> visited = new HashSet<>();
        Deque<Integer> toVisit = new ArrayDeque<>();
        toVisit.add(0);
        visited.add(0);

        while (!toVisit.isEmpty()) {
            int chamberId = toVisit.remove();
            for (int neighbourId : adjacency.getOrDefault(chamberId, Set.of())) {
                if (visited.add(neighbourId)) {
                    toVisit.add(neighbourId);
                }
            }
        }
        return visited;
    }

    private int degreeOf(DungeonResult result, int chamberId) {
        return buildAdjacency(result).getOrDefault(chamberId, Set.of()).size();
    }

    private Map<Integer, Set<Integer>> buildAdjacency(DungeonResult result) {
        Map<Integer, Set<Integer>> adjacency = new HashMap<>();
        for (ChamberConnection connection : result.connections()) {
            adjacency.computeIfAbsent(connection.fromChamberId(), id -> new HashSet<>())
                    .add(connection.toChamberId());
            adjacency.computeIfAbsent(connection.toChamberId(), id -> new HashSet<>())
                    .add(connection.fromChamberId());
        }
        return adjacency;
    }
}
